---

services:
  mdfanchanger:
    container_name: MD_Fan_Changer
    image: yuruc3/md1200_fan_controll:v2-flux
    env_file: md1200.env
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: false
