---

services:
  mdfanchanger:
    container_name: MD_Fan_Changer
    # build: ./
    # image: dm1200fanchanger:V1
    image: yuruc3/md1200_fan_controll:v1
    environment:
      - baud_rate: ${baud_rate:-38400} 
      - serial_adapter=${serial_adapter:-"/dev/ttyUSB0"} 
      - wait_time: ${wait_time:-1}
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: false
