---

services:
  mdfanchanger:
    container_name: MD_Fan_Changer
    build: ./
    image: dm1200fanchanger:V1
    environment:
      - baud_rate: ${baud_rate:-38400} 
      - serial_adapter=${serial_adapter:-"/dev/ttyUSB0"} 
      - wait_time: ${wait_time:-300}
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: false
